name: number_paginator
description: A Flutter paginator widget for switching between pages.
version: 1.1.1
homepage: https://github.com/WieFel/number_paginator

environment:
  flutter: ">=1.17.0"
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Just arrow buttons'
    path: screenshots/num1.png
  - description: 'Arrow buttons + number buttons'
    path: screenshots/num2.png
  - description: 'Arrow buttons + scrollable number buttons'
    path: screenshots/scrollable_numbers_centered.png
  - description: 'Arrow buttons + dropdown for choosing specific page number'
    path: screenshots/num3.png
  - description: 'Arrow buttons + build any custom view for the central part'
    path: screenshots/num4.png