name: number_paginator
description: A Flutter paginator widget for switching between pages.
version: 1.0.1
homepage: https://github.com/WieFel/number_paginator

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'First variant: hidden numbers, just arrow buttons.'
    path: screenshots/num1.png
  - description: 'Second variant: arrow buttons + number buttons.'
    path: screenshots/num2.png
  - description: 'Third variant: arrow buttons + dropdown for choosing specific page number.'
    path: screenshots/num3.png
  - description: 'Fourth variant: arrow buttons + build any custom view for the central part.'
    path: screenshots/num4.png