name: Deploy to web

on:
  push:
    tags:
      - '*'

jobs:
  deploy-for-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --enable-web
      - run: flutter pub get
      - name: Build for web
        working-directory: example/
        run: flutter build web --release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: example/build/web # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch